### ISSUE TITLE
Compatability issue with ASP.NET Core 1.0

### ISSUE THREAD

**Issue by Legogris** [pauldotknopf/JavaScriptViewEngine#5]
When building and running with the newly released ASP.NET Core 1.0, it fails on runtime:

```
System.TypeLoadException
Could not load type 'Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionExtensions' from assembly 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
```

```
 System.Reflection.TargetInvocationException
Exception has been thrown by the target of an invocation.

at System.RuntimeMethodHandle.InvokeMethod(object target, Object[] arguments, Signature sig, bool constructor)


at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(object obj, Object[] parameters, Object[] arguments)


at System.Reflection.RuntimeMethodInfo.Invoke(object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)


at System.Reflection.MethodBase.Invoke(object obj, Object[] parameters)


at Microsoft.AspNetCore.Hosting.Internal.ConfigureServicesBuilder.Invoke(object instance, IServiceCollection exportServices)


at Microsoft.AspNetCore.Hosting.Internal.<>c__DisplayClass4_0.<Build>b__0(IServiceCollection services)


at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)


at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()


at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()

```

on `services.AddJsEngine();` in `Startup.cs`.

**Comment by Legogris** [comment]
See http://stackoverflow.com/questions/38062850/typeloadexception-using-postgresql-with-asp-net-core-identity/38067694

**Comment by pauldotknopf** [comment]
I am still working on the 1.0.0 RTM upgrade. There was an environment issue this weekend preventing me from doing it.

I will keep you updated when it is done.

**Comment by pauldotknopf** [comment]
The latest version (1.3.0) on NuGet now supports 1.0.

**Comment by Legogris** [comment]
@pauldotknopf : Awesome, thanks for the fast update :)
Any idea of when this will be up on NuGet?

**Comment by pauldotknopf** [comment]
It is now.

https://www.nuget.org/packages/JavaScriptViewEngine.MvcCore1/

https://www.nuget.org/packages/JavaScriptViewEngine.Mvc5/
